name: Vale checks

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  check-all-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Documentation Quality Checks
        uses: errata-ai/vale-action@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}